### ISSUE TITLE
节点列表支持收起/展开

### ISSUE THREAD

**Issue by urkbio** [moonheart/Clasharp#11]
proxies 选择不太方便，我看 Netflix 需要手动选择解锁的节点，用这个客户端不太便捷，列表太多了，每个分类不能收起。不过功能够用，配置好了也很方便。希望后续更新越来越好用。
![屏幕截图 2023-01-16 184731](https://user-images.githubusercontent.com/114656103/212660915-b8f81e78-a6b3-45ed-bfd3-e6f0e7c08fa0.png)
![屏幕截图 2023-01-16 184756](https://user-images.githubusercontent.com/114656103/212660949-c68b5331-4b2f-4224-abb6-9ef47a6bb0c1.png)

**Comment by moonheart** [comment]
https://github.com/moonheart/Clasharp/actions/runs/3935926134
已添加收起/展开功能， 请尝试 action 中的 Release 版本。
